#!/bin/bash
export  SUBSCRIPTION_ID=""
export RESOURCE_GROUP=""
export WORKSPACE_NAME=""
export EXPERIMENT_NAME=""
export CLUSTER_NAME=""
export STORAGE_ACCOUNT_NAME=""
export STORAGE_CONTAINER_NAME=""